from django import forms

class ProjectEvalForm(forms.Form):
    project_id = forms.IntegerField()
    judge_email = forms.CharField(max_length=128)
    dp_a = forms.IntegerField()
    dp_b = forms.IntegerField()
    dp_c = forms.IntegerField()
    dp_d = forms.IntegerField()
    dp_e = forms.IntegerField()
    dp_f = forms.IntegerField()
    dp_g = forms.IntegerField()
    dp_h = forms.IntegerField()
    p_a = forms.IntegerField()
    p_b = forms.IntegerField()
    p_c = forms.IntegerField()
    p_d = forms.IntegerField()
    econ_consideration = forms.BooleanField()
    envi_consideration = forms.BooleanField()
    sust_consideration = forms.BooleanField()
    manu_consideration = forms.BooleanField()
    ethi_consideration = forms.BooleanField()
    heal_consideration = forms.BooleanField()
    soci_consideration = forms.BooleanField()
    poli_consideration = forms.BooleanField()
    comments = forms.CharField(max_length=512)
