# File: settings.py
# Description: Django settings for scoringsystem project.
#   Generated by 'django-admin startproject' using Django 2.2.6.

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&zy2in#3x$zapjv$2x02sf2x#!9)$)17!pvyjk=i&pwjn6zvw$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '6eea0fde.ngrok.io',
    '127.0.0.1',
    '39632aaa.ngrok.io',
]


# Application definition

INSTALLED_APPS = [
    'scoringsystem',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # created apps
    #'users',
    #'admin_site'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
]

# Backend authentication for custom user
# https://docs.djangoproject.com/en/2.2/howto/auth-remote-user/#configuration
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.RemoteUserBackend",   # authenticate using custom user
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'scoringsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoringsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'scoringsystem.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# by default Django will use custom created user
# https://docs.djangoproject.com/en/2.2/topics/auth/customizing/

AUTH_USER_MODEL = 'scoringsystem.judge'


# Login and Logout redirection

LOGOUT_REDIRECT_URL = 'home' # redirect logout to login
LOGIN_REDIRECT_URL = 'home'   # redirect login to home

# Email Settings for sending judge passwords

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = '174LW215'
EMAIL_HOST_USER = 'scusdscoringsystem@gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = 'True'
