# Generated by Django 2.2.6 on 2019-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='session',
            name='sessionNumber',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
