# Generated by Django 2.2.6 on 2019-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20191106_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='sessionNumber',
        ),
        migrations.AddField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
