# Generated by Django 2.2.6 on 2019-11-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_session_addjudge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='addJudge',
        ),
    ]
