# Generated by Django 2.2.6 on 2019-11-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Judge',
        ),
    ]
